server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php;

    location = /api {
        return 301 /api/;
    }

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        try_files $uri $uri/ =404;
    }

    location ~ ^/api/(.+\.php)$ {
        rewrite ^/api/(.*)$ /$1 break;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$uri;
        fastcgi_pass api-php:9000;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass api-php:9000;
    }

    location ~ /\. {
        deny all;
    }
}